name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches-ignore:
      - master

jobs:
  install-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install
        run: |
          python --version
          node --version
          npm --version

          npm install -g aws-cdk

          python -m pip install . --upgrade
          python -m pip list
